### ISSUE TITLE
Getting "TypeError: Cannot read property 'last-modified' of undefined" when running gulp-connect

### ISSUE THREAD

**Issue by Livshitz** [jshttp/fresh#27]
```
[12:13:53] Running server
/Users/.../node_modules/gulp-connect/node_modules/fresh/index.js:29
  var lastModified = res['last-modified'];
                        ^

TypeError: Cannot read property 'last-modified' of undefined
    at fresh (/Users/.../node_modules/gulp-connect/node_modules/fresh/index.js:29:25)
    at SendStream.isFresh (/Users/.../node_modules/gulp-connect/node_modules/send/index.js:372:10)
    at SendStream.send (/Users/.../node_modules/gulp-connect/node_modules/send/index.js:539:13)
    at onstat (/Users/.../node_modules/gulp-connect/node_modules/send/index.js:624:10)
    at FSReqWrap.oncomplete (fs.js:167:5)
```

gulp-connect setup:
`
connect.server({
	livereload: false,
	root: config.getDir() + '/',
	fallback: config.getDir() + '/index.html',
	https: true,
	host: '0.0.0.0',
});
`
Mostly happens when running with https:true and accessing the dev env from outside the network (I've opened a port to be forward from WLAN to my dev computer, for debugging). Anyway, only then this problem happened.

Fresh version: 0.3.0

**Comment by Livshitz** [comment]
Attempting to run latest Fresh version will result with this:
`
/Users/.../node_modules/gulp-connect/node_modules/fresh/index.js:53
    var etag = resHeaders['etag']
                         ^

TypeError: Cannot read property 'etag' of undefined
    at fresh (/Users/.../node_modules/gulp-connect/node_modules/fresh/index.js:53:26)
    at SendStream.isFresh (/Users/.../node_modules/gulp-connect/node_modules/send/index.js:372:10)
    at SendStream.send (/Users/.../node_modules/gulp-connect/node_modules/send/index.js:539:13)
    at onstat (/Users/.../node_modules/gulp-connect/node_modules/send/index.js:624:10)
    at FSReqWrap.oncomplete (fs.js:167:5)
`

Anyway, I'd suggest to add this line in case response, for some weird reason, got empty:
` if (res == null) res = {}; `

**Comment by dougwilson** [comment]
The resHeaders argument is required. If you're not going to pass in a value, just skip calling this function; you'll speed up the code :) since that would skip unnecessary calls.

I'll add some argument checks at the top of our module to throw with a "argument resHeaders is required" error to give a better error message :+1:

**Comment by dougwilson** [comment]
Looking at the stack trace again, I see the call is not coming from your code, but another module. I would file an issue on that module because that is where the bug is: it is calling this module and not passing in a required argument.
